[[regions]]
  id="cn470_0_0"
  description="CN470_0_0 (freq = 470.3)"
  common_name="CN470"
  [regions.gateway]
    force_gws_private=false
    [regions.gateway.backend]
      enabled="mqtt"
      [regions.gateway.backend.mqtt]
        topic_prefix="cn470_0_0"
        share_name="chirpstack"
        server="tcp://localhost:1883"
        username=""
        password=""
        qos=0
        clean_session=false
        client_id=""
        keep_alive_interval="30s"
        ca_cert=""
        tls_cert=""
        tls_key=""
  [regions.network]
    installation_margin=10
    rx_window=0
    rx1_delay=1
    rx1_dr_offset=0
    rx2_dr=0
    rx2_frequency=505300000
    rx2_prefer_on_rx1_dr_lt=0
    rx2_prefer_on_link_budget=false
    downlink_tx_power=-1
    adr_disabled=true
    min_dr=5
    max_dr=5
    enabled_uplink_channels=[0]
    [regions.network.rejoin_request]
      enabled=false
      max_count_n=0
      max_time_n=0
    [regions.network.class_b]
      ping_slot_dr=2
      ping_slot_frequency=0
