[backend]
type="semtech_udp"
  [backend.semtech_udp]
  udp_bind = "0.0.0.0:4700"
[integration]
marshaler="protobuf"
  [integration.mqtt]
  event_topic_template="cn470_0_0/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
  [integration.mqtt.auth]
  type="generic"
    [integration.mqtt.auth.generic]
    server="tcp://127.0.0.1:1883"
    username=""
    password=""
